//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colonia
    {
        public int IdColonia { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idMunicipio { get; set; }
    
        public virtual Municipios Municipios { get; set; }
    }
}
