//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppiApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TareaErikEntities2 : DbContext
    {
        public TareaErikEntities2()
            : base("name=TareaErikEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colonia> Colonia { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
    }
}
